sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cqrdA5g0IeXllrSHCvNArb6Ystp/80EsXI+PaKJy+iCFggnnUe7zbBGwvksKw88MnJbw4PJTAOA47KlOfGAEw+FWD9jP9+ZBx1o4H39Da1a+D9FMBGMGlpp8jBm4fahad5SIPKlH776adQSZT9bVk72sNZT4wHU3q3KWgM4qG7eS8tzDEaMP6u0wurVc17pFGObZpccxriGeMwFf47C2Dleges4YBjbf1IWnfx8JvC5LHMGSE88Bv5sIrG0veuz/ndJjPLa7Wr+xefKZXtAU3dSfp5r5CKVXHlETHRm131BbxQi5hN0ZR0h/AudXz52j2ZxdqzgHnpEdRoJx5+0KSIaj07r22am4GQWrQ6Y2ukkpQUjMJodHSlCi4pKhXz+hOFEH3iZTLST7D1dlDth/+hfiJKab1KFWTVzl7zVa2KViznyVBq/VpJqgAVUVamh0xtRoXSL490z7UGKhVKt04HwvDrYweTHpf7uhjWDLrvmO0jSS0HE1nwQvAKf35k9gzLnFl9YRtkFSH7u1pyCla7hmtuBfB25Sz1ly6IwRffpLt2xpsyoPbCB3JSkG880Z1vIRx0uNcsnmBg7+MbFbp5SR9CNLoiqkWjmMhf58SNPhuhTLqDjIepAsIIaHjQYRAEhgsoFokAuQVwR5OdqopgEhBbOv2OfTkjLrDb6i5KQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Worldwide-Effects-of-Nuclear-War--Some-Perspectives_684
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy